using System;
using UnityEngine;

public abstract class WeaponAction : MonoBehaviour, IWeaponAction
{
    [SerializeField, Tooltip("—­‚ßUŒ‚‘æ1’iŠK")] protected float _chargeLevel1 = 1f;
    [SerializeField, Tooltip("—­‚ßUŒ‚‘æ2’iŠK")] protected float _chargeLevel2 = 3f;

    [Tooltip("")] 
    bool _unStored = true;
    [Tooltip("—­‚ßUŒ‚‚Ì—­‚ßŠÔ")] 
    protected float _chrageCount = 0;
    [Tooltip("•Ší–¼")] 
    protected string _weaponName;
    [Tooltip("Player‚ÌAnimator‚ğŠi”[‚·‚é•Ï”")]
    protected Animator _animator = default;
    [Tooltip("WeaponBase‚ğŠi”[‚·‚é•Ï”")] 
    protected WeaponBase _weaponBase = default;
    [Tooltip("PlayerAnimationState‚ğŠi”[‚·‚é•Ï”")]
    PlayerAnimationState _state;

    public abstract void WeaponChargeAttackMethod(float chrageCount);
    public virtual void Enable() { }

    void OnEnable()
    {
        if(_unStored)
        {
            Enable();
            _state = PlayerAnimationState.Instance;
            _animator = PlayerContoller.Instance.GetComponent<Animator>();
            _weaponBase = GetComponent<WeaponBase>();
            _unStored = false;
        }
    }
   
    public void WeaponAttack(string weaponName)
    {
        if (!_state.AbleInput) return;

        ////’ÊíUŒ‚‚Ìˆ—
        if (Input.GetButtonDown("Attack"))
        {
            _animator.SetTrigger(weaponName);
        }

        //—­‚ßUŒ‚‚Ìˆ—(‹|–î‚ÌƒAƒjƒ[ƒVƒ‡ƒ“‚à‚±‚Ìˆ—j
        if (Input.GetButton("Attack") && _chrageCount < _chargeLevel2)
        {
            _chrageCount += Time.deltaTime;
        }
        else if (Input.GetButtonUp("Attack"))
        {
            if(_chrageCount > 0f)
            {
                WeaponChargeAttackMethod(_chrageCount);
            }
            _chrageCount = 0f;
        }

        _animator.SetBool("Charge", Input.GetButton("Attack"));
    }

    
}
